<Pers>:
    size: 14, 14
    canvas:
        Color:
            rgba: 1, 0, 1, 1
        Ellipse:
            pos: self.pos
            size: self.size 

<Test_button>:
    text: "test_move"

<Test_label>:
    text: "LABEL"
    pos: 300, 300

<NineTest>:

    player: _player
    btn: _btn
    label1: _label1

    Pers:
        id: _player
        pos: 100, 100

    Test_button:
        id: _btn

    Test_label
        id: _label1