# File name: nine_test.kv

<Player>:
    size: 24, 24
    canvas:
        Color:
            rgba: 0, 1, 1, 1
        Rectangle:
            pos: self.pos
            size: self.size 

<Blok>:
   
    size: 10, 100
    canvas:
        Rectangle:
            pos: self.pos
            size: self.size

<NineTest>:
    player: _player_apponent
    blok: _blok_width
    #blok_height: _blok_height
    blok_base: _blok_base

    Player:
        id: _player_apponent 
        pos: 200, 200

    Blok:
        id: _blok_width
        pos: root.width - 10, 0
        size: 10, root.height

    Blok:
        #id: _blok_height
        id: _blok_base
        pos: 0, 0
        size: 10, root.height

    Blok:
        #id: _blok_width
        pos: 0, 0
        size: root.width, 10

    Blok:
        #id: _blok_width
        pos: 10, root.height - 10
        size: root.width, 10
    