<Pers>:
    size: 14, 14
    canvas:
        Color:
            rgba: 1, 0, 1, 1
        Ellipse:
            pos: self.pos
            size: self.size 

<Test_button>:
    size: 100, 30

<Blok>:
   
    size: 10, 100
    canvas:
        Color:
            rgba: 0, 1, 1, 1
        Rectangle:
            pos: self.pos
            size: self.size

<NineTest>:

    player: _player
    btn: _btn
    btn2: _btn2
    btn3: _btn3

    Pers:
        id: _player
        pos: 100, 100

    Test_button:
        id: _btn
        text: "move -> "
        pos: 10, 10

    Test_button:
        id: _btn2
        text: "<- move"
        pos: 200, 10

    Test_button:
        id: _btn3
        text: "^"
        pos: 500, 10

    Blok:
        pos: 10, root.height - 10
        size: root.width, 10