# File name: nine_test.kv

<Pers>:
    size: 14, 14
    canvas:
        Color:
            rgba: 1, 0, 1, 1
        Ellipse:
            pos: self.pos
            size: self.size 

<Player>:
    size: 12, 12
    canvas:
        Color:
            rgba: 0, 1, 1, 1
        Ellipse:
            pos: self.pos
            size: self.size 

<Blok>:
   
    size: 10, 100
    canvas:
        Color:
            rgba: 0, 1, 1, 1
        Rectangle:
            pos: self.pos
            size: self.size

<Blok2>:
   
    size: 10, 100
    Color:
        rgba: 0, 1, 1, 1
    canvas:
        Rectangle:
            pos: self.pos
            size: self.size

<NineTest>:
    player: _player_apponent
    player2: _player_apponent2

    pers: _pers

    mov_rig: _mov_rig

    #blok: _blok_width
    #blok_base: _blok_base
    #blok_down: _blok_down
    #blok_down2: _blok_down2
    #blok_pol: _blok_pol
    #stop_label: _stop_label

    Player:
        id: _player_apponent 
        pos: 200, 400

    Player:
        id: _player_apponent2 
        pos: 200, 450
        size: 14, 14

    #Blok:
        #id: _blok_width
        #pos: root.width - 10, 0
        #size: 10, root.height

    #Blok:
        #id: _blok_base
        #pos: 0, 0
        #size: 10, root.height

    #Blok:
        #id: _blok_down2
        #pos: 100, 50
        #size: 200, 10

    #Blok:
        #id: _blok_down
        #pos: 100, 300
        #size: 950, 10

    Label:
        text: 'Some'
        markup: True
        shorten: True
        ellipsis_options: {'color':(1,0.5,0.5,1),'underline':True}
        pos: 400, 300
        
    #Blok:
        #id: _blok_pol
        #pos: 0, 0
        #size: root.width, 10
        
    Blok:
        pos: 10, root.height - 10
        size: root.width, 10

    Pers:
        id: _pers
        pos: 30, 30

    Button:
        id: _mov_rig
        text: "x+"
        pos: 20, root.height - 30
        size: 30, 20
        #on_press: _pers.move_right()

    Button:
        text: "x-"
        pos: 120, root.height - 30
        size: 30, 20
        
    