# File name: nine_test.kv

<Player>:
    size: 12, 12
    canvas:
        Color:
            rgba: 0, 1, 1, 1
        Rectangle:
            pos: self.pos
            size: self.size 

<Blok>:
   
    size: 10, 100
    canvas:
        Rectangle:
            pos: self.pos
            size: self.size

<Blok2>:
   
    size: 10, 100
    canvas:
        Rectangle:
            pos: self.pos
            size: self.size

<NineTest>:
    player: _player_apponent
    player2: _player_apponent2

    #blok: _blok_width
    #blok_base: _blok_base
    #blok_down: _blok_down
    #blok_down2: _blok_down2
    #blok_pol: _blok_pol
    stop_label: _stop_label

    Player:
        id: _player_apponent 
        pos: 200, 400

    Player:
        id: _player_apponent2 
        pos: 200, 450

    #Blok:
        #id: _blok_width
        #pos: root.width - 10, 0
        #size: 10, root.height

    #Blok:
        #id: _blok_base
        #pos: 0, 0
        #size: 10, root.height

    #Blok:
        #id: _blok_down2
        #pos: 100, 50
        #size: 200, 10

    #Blok:
        #id: _blok_down
        #pos: 100, 300
        #size: 950, 10

    Label:
        id: _stop_label
        text: "|"
        size: 12, 12
        pos: 400, 300
        
    #Blok:
        #id: _blok_pol
        #pos: 0, 0
        #size: root.width, 10
        
    Blok:
        pos: 10, root.height - 10
        size: root.width, 10
    